---
# vars file for php
phpextensions:
  - php72-php-fpm
  - php72-php-gd
  - php72-php-json
  - php72-php-mbstring
  - php72-php-mysqlnd
  - php72-php-xml
  - php72-php-xmlrpc
  - php72-php-opcache
  - php72-php-xml
  - php-soap
  - php-bcmath
  - php-bz2
  - php-calendar
  - php-ctype
  - php-curl
  - php-dom
  - php-exif
  - php-fileinfo
  - php-ftp
  - php-gd
  - php-gettext
  - php-iconv
  - php-intl
  - php-json
  - php-mbstring
  - php-mysqlnd
  - php-pdo
  - php-phar
  - php-posix
  - php-shmop
  - php-simplexml
  - php-sockets
  - php-sqlite3
  - php-sysvmsg
  - php-sysvsem
  - php-sysvshm
  - php-tokenizer
  - php-xml
  - php-xmlwriter
  - php-xsl
  - php-mysqli
  - php-pdo_mysql
  - php-pdo_sqlite
  - php-wddx
  - php-xmlreader
  - php-zip
