# roles/amazon-ssm-agent/tasks/main.yml
- name: Install rpm file for Redhat Family (Amazon Linux, RHEL, and CentOS) 32/64-bit
  become: yes
  become_user: root
  yum:
      name: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm"
      state: present
  when: ansible_os_family == 'RedHat'

- name: start amazon-ssm-agent
  systemd:
    state: started
    daemon_reload: yes
    name: amazon-ssm-agent

- name: enable amazon-ssm-agent
  systemd:
    enabled: yes
    daemon_reload: yes
    name: amazon-ssm-agent
